// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj02iiINeu7W5nUpAwc90cNH6gDxPnzD4',
    appId: '1:301094002417:web:27a9adb73892f7be691350',
    messagingSenderId: '301094002417',
    projectId: 'news-app-478cb',
    authDomain: 'news-app-478cb.firebaseapp.com',
    storageBucket: 'news-app-478cb.appspot.com',
    measurementId: 'G-H4FFM2ED4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRVGtU93xjUyWyvBJ6bLZp7qCXgKq2MOE',
    appId: '1:301094002417:android:dc70bc0baecde6d2691350',
    messagingSenderId: '301094002417',
    projectId: 'news-app-478cb',
    storageBucket: 'news-app-478cb.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzOZGM-nTUechxrChDRneYHfMp4RNPZBw',
    appId: '1:301094002417:web:e3ff91e69e97428b691350',
    messagingSenderId: '301094002417',
    projectId: 'news-app-478cb',
    authDomain: 'news-app-478cb.firebaseapp.com',
    storageBucket: 'news-app-478cb.appspot.com',
    measurementId: 'G-25SLHYGF1L',
  );

}